alimentacao = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]), DATA_TAB[TIPODESPESA] = "FORNECIMENTO DE ALIMENTAÇÃO DO PARLAMENTAR")+0
aluguel de veiculos = CALCULATE([vei 1] + [vei 2] + [vei 3])+0
combustivel = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]), DATA_TAB[TIPODESPESA] = "COMBUSTÍVEIS E LUBRIFICANTES.")+0
divulgacao = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]), DATA_TAB[TIPODESPESA] = "DIVULGAÇÃO DA ATIVIDADE PARLAMENTAR.")+0
escritorio = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]), DATA_TAB[TIPODESPESA] = "MANUTENÇÃO DE ESCRITÓRIO DE APOIO À ATIVIDADE PARLAMENTAR")+0
HOSPEDAGEM = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]), DATA_TAB[TIPODESPESA] = "HOSPEDAGEM ,EXCETO DO PARLAMENTAR NO DISTRITO FEDERAL.")+0
pass 1 = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]), DATA_TAB[TIPODESPESA] = "PASSAGEM AÉREA - SIGEPA")+0
pass 2 = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]), DATA_TAB[TIPODESPESA] = "PASSAGEM AÉREA - RPA")+0
pass 3 = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]), DATA_TAB[TIPODESPESA] = "PASSAGEM AÉREA - REELBOLSO")+0
pass 4 = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]), DATA_TAB[TIPODESPESA] = "PASSAGENS TERRESTRES, MARÍTIMAS OU FLUVIAIS")+0
passagem = [pass 1]+[pass 2]+[pass 3]+0
quantdep = CALCULATE(DISTINCTCOUNT(DATA_TAB[NOME]))
total = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]))
vei 1 = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]), DATA_TAB[TIPODESPESA] = "LOCAÇÃO OU FRETAMENTO DE VEÍCULOS AUTOMOTORES")
vei 2 = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]), DATA_TAB[TIPODESPESA] = "LOCAÇÃO OU FRETAMENTO DE EMBARCAÇÕES")
vei 3 = CALCULATE(SUM(DATA_TAB[VALORDOCUMENTO]), DATA_TAB[TIPODESPESA] = "LOCAÇÃO OU FRETAMENTO DE AERONAVES")